// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'itemPicker': string;
  'search': string;
}
declare var cssExports: CssExports;
export = cssExports;
